# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [19]:
import numpy as np

print(np.zeros((2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [20]:
print(np.empty((2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]


### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [34]:
# 記得先 Import 正確的套件

from numpy.random import default_rng
rng = default_rng()

normal = np.random.randn(2, 3)
random = np.random.random((3,2))
integers = np.random.randint(0, 10, size=(3,2))

print(normal)
print(random)
print(integers)

[[ 1.42341454  1.6385868   1.02290451]
 [-0.34328234  0.05746776 -0.68741384]]
[[0.01928149 0.09494528]
 [0.04362052 0.58605301]
 [0.18364743 0.85537151]]
[[4 5]
 [5 7]
 [0 8]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [5]:
m = 20
n = 40

np.linspace( 20, 40, 6 )

[[34. 33. 38.]
 [39. 23. 20.]]


In [41]:
m = 20
n = 40

a=np.random.rand(2,3)*(n-m)
b=a
print(a)
print(b%1) #取b/1的餘數
print(m+a-b%1) #從20開始，加a，去掉b(小數的部分)

[[ 7.01826724 14.85234322 11.80750956]
 [16.92994112  1.74253385 10.51609912]]
[[0.01826724 0.85234322 0.80750956]
 [0.92994112 0.74253385 0.51609912]]
[[27. 34. 31.]
 [36. 21. 30.]]


In [25]:
np.arange( 10, 30, 5 )
# array([10, 15, 20, 25])

array([10, 15, 20, 25])

In [26]:
np.linspace( 0, 2, 3 )
# array([0. 1. 2.])

array([0., 1., 2.])

In [27]:
np.logspace( 0, 2, 3 )
# array([1. 10. 100.])

array([  1.,  10., 100.])

In [16]:
np.zeros((2, 3))
# 建立由 0 組成的 2x3 陣列

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.ones((2, 3))
# 建立由 1 組成的 2x3 陣列

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.full((2, 3), 9)
# 建立由 9 組成的 2x3 陣列

array([[9, 9, 9],
       [9, 9, 9]])