# [作業目標]

1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。
2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



# 作業 

### 1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。



In [13]:
import numpy as np


In [16]:
a = np.arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [18]:
a[(a>2)&(a<7)]*=-1
print(a)

[ 0  1  2 -3 -4 -5 -6  7  8  9 10 11]


### 2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



In [19]:
A = np.random.rand(3, 6)
print(A)
print(A[(A>0.5)].size)

[[0.5270618  0.62901448 0.54314181 0.33804086 0.47043016 0.5007758 ]
 [0.60905355 0.5603533  0.05092711 0.14578949 0.58196488 0.85663549]
 [0.31868947 0.45354549 0.11632743 0.23046132 0.35900683 0.73940026]]
9
